version: '3.4'

services:
  project.microservices:
    image: ${DOCKER_REGISTRY-}projectmicroservices
    build:
      context: .
      dockerfile: Project.Microservices/Dockerfile
    ports:
        - 7000:80
        - 7100:443
  api.taxajuros:
    image: ${DOCKER_REGISTRY-}apitaxajuros
    build:
      context: .
      dockerfile: Services/API.TaxaJuros/Dockerfile
    ports:
        - 7001:80
        - 7101:443
  api.calculajuros:
    image: ${DOCKER_REGISTRY-}apicalculajuros
    build:
      context: .
      dockerfile: Services/API.CalculaJuros/Dockerfile
    ports:
        - 7002:80
        - 7102:443